sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"
after_success:
  - npm run semantic-release
env:
  matrix:
    - TEST_CLIENT=node
    - TEST_CLIENT=selenium:firefox
    - TEST_CLIENT="saucelabs:internet explorer:10:Windows 8"
