sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"
after_success:
  - npm run semantic-release
env:
  global:
    # saucelabs
    - secure: I2VbFJYNFTuKd+3c78p47YCsippZha0lWCkFgydET30siL8z57XnfGRpXUvKNhMg12T+qVrZTUhTCqYKCaTjQPNPMc9SnlDrgZdgaVDg7GMStne1ilZ4V/MQHpj8s8+5jSR8dhBTT9uKJ87SWnEjU9aiJ8bCe4YkP52lVyqMv00lP3Nfo7khSuSlPlLD/oWXKq1q3RHNTyQ04uR8ysXLuOKv5/BCJfrsfebta5lKARtDoMOY9xQf+sYeCBr5D7H9uXmxTawA3b/ID7YcTBQuzUGk6HWqbsMw36UrYIE4yHpmbfhe2BCghRgwRW0JgTjfrk2Yts4kXqPKCtoMTJt8FnRHR3uzNSAj7Z71hTt00DAJHb5VYvbPuiL7NKhLJqXrfJnMSg1bFIme9Fj4CK9oOUAlbPWlYwxai0FlVdlfHaAdX6nAVWbBbWrGgKC4BaqK2tNF20Dbli6Plo81mDRVnV9LqWpmKY8ZnZmjB2LwjgQPH3FZknBRkpok4bEDUQSWdLA/BFWvJ+m383TaGJpgtPaulpTDY/HB+DXzM99wXqUnfZnfaJGVB+NLBqHszzxeajS66fGInWGKdS+whQUmnW0hcDEh1C2+rbg0kYrc4m3uuq3PSTH3ItTE2qJbw2uz66WgYiD87hqMkCV7QoMXU13ZGrETuGVo5tFW6NCL0CI=
    - secure: QOe9LBlIih90tQA9AtWHB2krxhGmjW/sIfm+BkAavflEWNPZu/NxRscMDZnjLkoFW7peR9F+Pqfp3BdTrNwHKB5Fsm2tjO5qGChZFHm6gFNwdWRanjcbJGv+k48PzNml70WKvua4lPSFtxau7uSD+j2L4D/pZmHpN/SzmDBovOx/oTPTPZ94OTB7OogjDcPHR+mLbRYvFYa/9BEeEkh7aZ/VXofoIsKNm7GAKSY6C8jWPwtbw/81AqbLoswZfg+QKhx3JwRdZUI8ns4pEsjo3I+o5w1m/qxJepnpAA0Qu5bTfLx1roj8NnJnavvSVuwloEBC+BuBFAB05RTjnZWNIJc4XI1lxgregvVEGH4v2+MegamDMEdW45q0t9yY96u0haJ+S94ZSsRCV4KLLqiFq/coSZyjj6/DHVegGDSzaxOwVVKhrB+cymOBkzIPjJ4mD4QzYXSqVIz2IZnqi0U3Ba0VIwq6yhHDsjFbf08W6fu08EIg4tVbJsry8R7AI0Ich8KqiS/yDD2BBiWh6bOj5VH1i3JQoBn8CSnq6Nc9+q/49OPa+Zb/AFXUOZF+gkjmtR0e78Y1eBiYMkFskbCmwff6H3IeDE1qPMjmSKY22BHim84jika49w1RI6kAzrcKUkGW0Gj+fcrYZj7WIyeqFOcboa8ooH/STNZ4AlOmOfI=
  matrix:
    - TEST_CLIENT=node
    - TEST_CLIENT=selenium:firefox
    - TEST_CLIENT="saucelabs:internet explorer:10:Windows 8"
